# Part 1

In [1]:
import numpy as np

In [13]:
def read_input(file):
    trees = np.loadtxt(file, dtype=str)
    # Divide trees intro individual columns by separating the strings into integers
    trees = np.array([list(t) for t in trees])
    # Convert elements of trees to integers
    trees = trees.astype(int)
    return trees

In [19]:
# An element is visible from the edges if all elements on either side above and below are smaller than itself
# Function that checks which elements are visible from the edge
def visible_from_edge(trees):
    # Initialize array of zeros
    visible = np.zeros(trees.shape, dtype=int)
    # Initialize the edge elements of visible to 1 as these are always visible
    visible[0,:] = 1
    visible[-1,:] = 1
    visible[:,0] = 1
    visible[:,-1] = 1
    # Loop over all columns except the first and last
    for i in range(1, trees.shape[1]-1):
        # Loop over all rows except the first and last
        for j in range(1, trees.shape[0]-1):
            # Check if element is visible from the edge
            if (trees[j,i] > trees[:j,i].max() or trees[j,i] > trees[j+1:,i].max()
                or trees[j,i] > trees[j,:i].max() or trees[j,i] > trees[j,i+1:].max()):
                visible[j,i] = 1
    return visible

Test on test input

In [21]:
test_trees = read_input('test_input.txt')
visible_from_edge(test_trees).sum()

21

On real input

In [22]:
trees = read_input('input.txt')
visible_from_edge(trees).sum()

1843

# Part 2

In [66]:
# Calculate scenic score by multiplying the number of visible trees in each direction
def scenic_score(trees):
    # Initialize array of zeros
    score = np.ones(trees.shape, dtype=int)
    # Calulate the viewing distance for each element in each direction
    # Loop over all rows
    for i in range(trees.shape[0]):
        # Loop over all columns
        for j in range(trees.shape[1]):
            # Calculate viewing distance in each direction by looking how many elements you have to
            # move in each direction before you find an element that is larger than the current element
            # Moving left and right is done by looking at the elements in the same row
            # print(f'\n Element [{i}, {j}]: {trees[i,j]}')
            if j > 0:
                # Moving left
                dist_to_left = 1
                tmp_tree = trees[i,j-dist_to_left]
                while tmp_tree < trees[i,j]:
                    # Check if you are not at the edge of the array
                    if j-dist_to_left <= 0:
                        break
                    dist_to_left += 1
                    tmp_tree = trees[i,j-dist_to_left]
                # print(f' dist_to_left: {dist_to_left}')
                score[i,j] *= dist_to_left
            if j < trees.shape[1]-1:
                # Moving right
                dist_to_right = 1
                tmp_tree = trees[i,j+dist_to_right]
                while tmp_tree < trees[i,j]:
                    # Check if you are not at the edge of the array
                    if j+dist_to_right >= trees.shape[1]-1:
                        break
                    dist_to_right += 1
                    tmp_tree = trees[i,j+dist_to_right]
                # print(f' dist_to_right: {dist_to_right}')
                score[i,j] *= dist_to_right
            if i > 0:
                # Moving up
                dist_to_up = 1
                tmp_tree = trees[i-dist_to_up,j]
                while tmp_tree < trees[i,j]:
                    # Check if you are not at the edge of the array
                    if i-dist_to_up <= 0:
                        break
                    dist_to_up += 1
                    tmp_tree = trees[i-dist_to_up,j]
                # print(f' dist_to_up: {dist_to_up}')
                score[i,j] *= dist_to_up
            if i < trees.shape[0]-1:
                # Moving down
                dist_to_down = 1
                tmp_tree = trees[i+dist_to_down,j]
                while tmp_tree < trees[i,j]:
                    # Check if you are not at the edge of the array
                    if i+dist_to_down >= trees.shape[0]-1:
                        break
                    dist_to_down += 1
                    tmp_tree = trees[i+dist_to_down,j]
                # print(f' dist_to_down: {dist_to_down}')
                score[i,j] *= dist_to_down
            # print(f' score: {score[i,j]}')
    return score


In [67]:
test_trees

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

Test trees

In [68]:
scenic_score(test_trees)

array([[ 4,  1,  2, 12,  3],
       [ 1,  1,  4,  1,  2],
       [16,  6,  1,  2,  1],
       [ 1,  1,  8,  3, 12],
       [ 1,  4,  1, 12,  1]])

Real input

In [69]:
scenic_score(trees)

array([[ 2,  1,  2, ...,  4,  1,  1],
       [ 1,  8, 42, ...,  6,  2,  2],
       [ 3,  1,  1, ...,  4,  1,  1],
       ...,
       [32,  1,  1, ...,  1,  1,  9],
       [ 1,  1,  6, ...,  2, 15,  1],
       [ 1,  3,  2, ...,  6,  1,  1]])

In [71]:
np.max(scenic_score(trees))

180000